### Image
image:
  image: kestra/kestra
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []


### Configurations for deployments
configuration: {}


### Secrets for deployments
secrets: {}


### Deployments
deployments:
  webserver:
    enabled: true
    kind: Deployment
    command:
      - sh
      - -c
      - "/app/kestra server webserver"
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  executor:
    enabled: true
    kind: Deployment
    command:
      - sh
      - -c
      - "/app/kestra server executor"

  indexer:
    enabled: true
    kind: Deployment
    command:
      - sh
      - -c
      - "/app/kestra server indexer"

  worker:
    enabled: true
    kind: DaemonSet
    command:
      - sh
      - -c
      - "/app/kestra server worker --thread=16"


### Kafka
kafka:
  enabled: false
  imageTag: "5.3.2"


### ElasticSearch
elasticsearch:
  enabled: false
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  clusterName: "es-kestra"


### Services
service:
  type: ClusterIP
  port: 8080
  annotations: {}

### Ingress
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


### Global Deployement
nameOverride: ""
serviceAccountName: ""

### Annotations for deployments
annotations: {}
podAnnotations: {}
initContainers: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumeMounts: []

extraVolumes: []

extraEnv: []


### Readiness / Liveness probe config.
### ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
readinessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
