{{- if .Values.configuration }}
{{ $merged := (merge (dict "Component" "configmap") $) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kestra.fullname" $merged }}
  labels:
  {{- include "kestra.labels" $merged | nindent 4 }}
data:
  application.yml: |
{{ .Values.configuration | toYaml | indent 4}}
  application-k8s.yml: |
    {{ include "kestra.k8s-config" $ | nindent 12 | indent 4}}
{{- end }}
