{{ range $name, $deployment := .Values.deployments }}
  {{- if $deployment.enabled -}}

{{ $merged := (merge (dict "Component" $name) $) -}}
apiVersion: apps/v1
kind: {{ $deployment.kind }}
metadata:
  name: {{ include "kestra.fullname" $merged }}
  labels:
    {{- include "kestra.labels" $merged | nindent 4 }}
  {{- with $.Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $deployment.kind "Deployment" }}
  replicas: {{ $deployment.replicaCount | default 1 }}
  {{- end }}
  {{- if $deployment.strategy }}
  strategy:
    {{- toYaml $deployment.strategy | nindent 4 }}
    {{ if eq $deployment.strategy.type "Recreate" }}rollingUpdate: null{{ end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kestra.selectorsLabels" $merged | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kestra.selectorsLabels" $merged | nindent 8 }}
      {{- with $.Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if $.Values.serviceAccountName }}
      serviceAccountName: {{ $.Values.serviceAccountName }}
      {{- end }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $.Values.initContainers }}
      initContainers:
      {{- toYaml $.Values.initContainers | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ default $.Values.terminationGracePeriodSeconds $deployment.terminationGracePeriodSeconds }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $name }}
          image: "{{ $.Values.image.image }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command:
            {{- toYaml $deployment.command | nindent 12 }}
          env:
            {{- if $.Values.extraEnv }}{{ toYaml $.Values.extraEnv | trim | nindent 12 }}{{ end }}
            {{- include "kestra.configurationPath" $ | nindent 12 }}
          volumeMounts:
            {{- if $.Values.extraVolumeMounts }}{{ toYaml $.Values.extraVolumeMounts | trim | nindent 12 }}{{ end }}
            {{- if $.Values.configuration }}
            - name: config
              mountPath: /app/confs/
            {{- end }}
            {{- if $.Values.secrets }}
            - name: secrets
              mountPath: /app/secrets/
            {{- end }}
            {{- if and ($.Values.deployments.worker.dind.enabled) (eq $name "worker") }}
            - name: docker-dind-socket
              mountPath: {{ $.Values.deployments.worker.dind.socketPath }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          {{- if $.Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.livenessProbe.path }}
              port: {{ $.Values.livenessProbe.port }}
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $.Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.readinessProbe.path }}
              port: {{ $.Values.readinessProbe.port }}
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml (default $.Values.resources $deployment.resources) | nindent 12 }}
        {{- if and ($.Values.deployments.worker.dind.enabled) (eq $name "worker") }}
        - name: {{ $.Chart.Name }}-{{ $name }}-docker-dind
          image: "{{ $.Values.deployments.worker.dind.image.image }}:{{ $.Values.deployments.worker.dind.image.tag }}"
          imagePullPolicy: {{ $.Values.deployments.worker.dind.image.pullPolicy }}
          args:
            {{- toYaml $.Values.deployments.worker.dind.args | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-dind-socket
              mountPath: {{ $.Values.deployments.worker.dind.socketPath }}
          resources:
            {{- toYaml $.Values.deployments.worker.dind.resources | nindent 12 }}
        {{- end }}
      {{- with default $.Values.nodeSelector $deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with default $.Values.affinity $deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with default $.Values.tolerations $deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if $.Values.extraVolumes  }}{{ toYaml $.Values.extraVolumes | trim | nindent 8 }}{{ end }}
        {{- if $.Values.configuration }}
        - name: config
          configMap:
            name: {{ template "kestra.fullname" (merge (dict "Component" "configmap") $) }}
            items:
              - key:  application.yml
                path: application.yml
              {{- if include "kestra.k8s-config" $ }}
              - key:  application-k8s.yml
                path: application-k8s.yml
              {{- end }}
        {{- end }}
        {{- if $.Values.secrets }}
        - name: secrets
          secret:
            secretName: {{ template "kestra.fullname" (merge (dict "Component" "secret") $) }}
              items:
              - key:  application-secrets.yml
                path: application-secrets.yml
        {{- end }}
        {{- if and ($.Values.deployments.worker.dind.enabled) (eq $name "worker") }}
        - name: docker-dind-socket
          emptyDir: {}
        {{- end }}
---
  {{- end }}
{{ end }}
