{{- if .Values.secrets }}
{{ $merged := (merge (dict "Component" "secret") $) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kestra.fullname" $merged }}
  labels:
    {{- include "kestra.labels" $merged | nindent 4 }}
type: Opaque
data:
  application-secrets.yml: {{.Values.secrets | toYaml | b64enc | quote }}
{{- end }}
