name: Helm Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          charts-folder: "charts"
          deploy-branch: gh-pages

      # Slack
      - name: Slack notification
        uses: 8398a7/action-slack@v2
        if: failure()
        with:
          status: ${{ job.status }}
          username: GitHub Actions
          icon_emoji: ':github-actions:'
          channel: '#git'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
